stellaGK/stella

- .gitignore
- .gitmodules
- Makefile
- scripts/build_pfunit
- scripts/ci_build_and_run.sh
- tests/unit/Makefile
- tests/unit/testSuites.inc
- tests/unit/test_simple.pf
- tests/unit/writing_tests.md
Adds unit testing infrastructure -- no useful tests yet, just a demonstration. I'll talk to Bob about getting some real tests in.
Most of this has been adapted from GS2.
The various parts are:
- `externals/pFUnit`: git submodule, so that pFUnit is always available and doesn't need to be installed separately
- `scripts/build_pfunit`: helper script to build the pFUnit submodule, or to download and build a tarball if git isn't available
- `tests/unit/Makefile`: rules and targets for building pFUnit test suite
- `tests/unit/test_simple.pf`: simple test module just so there's something in place for the time being
- `tests/unit/testSuites.inc`: essentially a list of pFUnit tests
- `tests/unit/writing_tests.md`: some documentation on writing pFUnit tests
> Add unit tests

- stella_io.fpp
`theta0` is created as both a dimension and variable in the netCDF file, but the variable has dimensions `(theta0, ky)`. This leads to the following error if the output file is read in with `xarray`:
> MissingDimensionsError: 'theta0' has more than 1-dimension and the same name as one of its dimensions ('theta0', 'ky'). xarray disallows such variables because they conflict with the coordinates used to label dimensions.
The cause of this is because when the `theta0` dimension is created in `stella_io.fpp` it reuses the `nakx_dim`, so the variables that have a `kx` dimension get a `theta0` dimension instead. This might be what is wanted, but I suspect not.
After this PR, in the output netCDF file, the `theta0` variable will have dimensions `(kx, ky)`, and the `kx` variable will have …
> Remove `theta0` dimension from netCDF output

- scripts/build_pfunit
Ensures that if `PFUNIT_VERSION_MAJOR` is set in the environment then this is the default pfunit version to try building.
This makes it slightly easier to control the version used when calling `build_pfunit` via make and if users have already set `PFUNIT_VERSION_MAJOR` for other codes.
> Minor change to build_pfunit to take value from environment

- tests/unit/testSuites.inc
- tests/unit/test_utils_convert.pf
Ports convert test from release 8.1 of GS2/utils to stella.
Nothing particularly exciting but may as well share it!
Only other shared module currently tested in utils is splines, but the code in the two modules is no longer the same so the tests do not port over.
> Port test of convert from gyrokinetics to stella

- species.f90
GCC11 is stricter about standards conformance it seems
> Fix for GCC11: Reorder variable and namelist declaration

- .github/workflows/tests.yml
- .gitignore
- Makefile
- scripts/ci_build_and_run.sh
- tests/integrated/Makefile
- tests/integrated/README.md
- tests/integrated/check_integrated_requirements.py
- tests/integrated/requirements.txt
- tests/integrated/simple/simple.in
- tests/integrated/simple/test_simple.py
This PR adds a framework for running integrated/system tests -- that is, running a whole `stella` simulation and verifying the outputs in same manner.
I've used Python to write this because a) it's generally installed everywhere, including on HPC systems, and b) the `pytest` framework does a lot of the heavy lifting in terms of finding and running the tests. I've also used `xarray` to read in the output files -- the plasma community is slowly converging on this as the de facto standard (see Tom Nicholas' excellent blogpost: https://hackmd.io/@TomNicholas/rkyERwcoO)
This does mean that in order to run the integrated tests you will need a few Python packages:
- pytest
- xarray
- netCDF4
- numpy
I've added the `make create-test-virtualenv` target to simplify installing these. If you don't …
> Add integrated test framework

- CITATION.cff
- LICENCE.md
Resolves #3 
@mabarnes @DenSto I've been a bit presumptive and assumed you're alright with the MIT licence.
CITATION.cff is in the [Citation File Format](https://citation-file-format.github.io), and basically is a way of letting people cite the _software_. It can also reference e.g. the stella paper.
I've included GS2 authors from before 2018 with `git log --reverse --pretty=tformat:'%an' --date=short --before 2018 | sort | uniq`. @mabarnes Let me know if that should be different.
> Add citation/copyright file, plus MIT licence

- Makefile
- Makefile.target_stella
Fixes a couple of issues I run into occasionally:
- `VPATH` can include paths outside of the `stella` project
- `make -j` can error if it tries to build `vmec_to_stella_geometry_interface` before `mini_libstell.a`
> Minor fixes for makefile

- Makefile.target_stella
Closes #10 
Second commit isn't strictly necessary, but shortens the output from `make` if there's nothing to rebuild
> Fix unnecessary rebuilds caused by #9

- .github/workflows/docs.yml
- .gitignore
- Makefile
- README.md
- docs/page/writing_documentation.md
- docs/stella_docs.md
- stella.f90
- stella_diagnostics.f90
- stella_io.fpp
This adds a Github Action that runs only on pushes to `master`. It runs Ford to build the documentation from `master`, then commits the built documentation to `gh-pages`. This will trigger Github to rebuild the website.
Unfortunately this means there's basically no way to preview the website except building it locally.
I stole the documentation on writing Ford documentation from the GS2 version I wrote: https://gyrokinetics.gitlab.io/gs2/page/developer_manual/writing_documentation.html
The TL;DR is "use `!>` in front of variables/subroutines/functions/modules/programs to turn a comment into a Ford doc-comment".
I've added a small smattering of docstrings to demonstrate what this looks like. They probably want checking.
> Automatically build documentation/website

- run_parameters.f90
- stella.f90
> Run a simulation up to code_time=tend.

- run_parameters.f90
- stella.f90
- stella_time.f90
- time_advance.f90
Before the maximum time step was the <delt> given in the <knob> namelist. However when we restart we do not want the restarted time step to be the maximum time step. Therefore I added a new variable <delt_max> which will set the maximum time step. If it is not mentioned, the previous behaviour of code_delt_max = delt will be retained.
> Added delt_max to the <knob> namelist.

- scripts/upgrade_inputs.py
This is perhaps a bit overkill for upgrading a single option, but it is easily expandable for future changes: add a new item to the `REPLACEMENTS` list and it will be handled automatically.
Here's what running it looks like on the previous version of `example.in` (i.e. as of 45e039722)
```console
$ ./scripts/upgrade_inputs.py --help
usage: upgrade_inputs.py [-h] [--force | --patch-only] [--quiet] files [files ...]
stella input file auto-upgrader
positional arguments:
files             Input files
optional arguments:
-h, --help        show this help message and exit
--force, -f       Make changes without asking
--patch-only, -p  Print the patches and exit
--quiet, -q       Don't print patches
$ ./scripts/upgrade_inputs.py example.in 
******************************************
Changes to …
```
> Add input file upgrader

- geo/stella_geometry.f90
- geo/vmec_geo.f90
- geo/vmec_interface/test_vmec_to_stella_geometry_interface.f90
- geo/vmec_interface/vmec_to_stella_geometry_interface.f90
- zgrid.f90
i) Bug in the stellarator symmetric twist and shift BC factor fixed.
ii) Now it is possible to choose automatically the length of the flux tube depending on the desired $dkx/dky$ if using stellarator symmetric twist and shift BC. This is done via the new input variable 'dkx_over_dky'.
> Stellarator symmetric twist and shift BC (bug and new functionality)

- response_matrix.fpp
> Avoid counting duplicate point when getting response

- parallel_streaming.f90
Avoids mismatched operands in periodic modes with nperiod > 1
> Generalisation for nperiod > 1 for periodic modes in parstream

- fields.fpp
- parallel_streaming.f90
Calls to `time_message` use the value of the passed time array to decide what to do, if we don't initialise the array then this behaviour is undefined.
> Make sure time arrays are initialised

- multibox.f90
Avoids potential seg faults during the end of a run.
> Avoid attempt to destroy multibox plans when not using multibox

- dissipation.f90
- fields.fpp
- sources.fpp
Avoids division by zero, which makes debugging with -ffpe-trap=invalid,overflow,zero a little easier.
> Avoiding dividing by zero in fields.fpp

- .github/workflows/docs.yml
This should hopefully ensure pip fetches a more recent version of jinja2
> CI: Setup python in docs build

- stella_io.fpp
- tests/integrated/restart/end_half_run.in
- tests/integrated/restart/full_run.in
- tests/integrated/restart/start_half_run.in
- tests/integrated/restart/test_restarting.py
Fixes #85
Previously, if a simulation was restarted and the new input file was
longer than the one in the netCDF file, we would hard error.
Now, the "number of lines" dimension is unlimited, so longer input
files can always be written. If the new input file is shorter, we
blank out the variable first.
Also adds a test for restarting simulations -- run a full length simulation, then two half-length ones. The final half-length output file should be identical to the full length one.
@rd1042 I reproduced your bug and this seems to fix it, but please could you double check it for your case?
> Fix bug with restarted simulations with longer input files

- .github/workflows/tests.yml
Add a workflow to the tests.yml file that checks the compilation and automatic numerical tests using a mac operating system. This is to protect against changes or test being made that are not compatible across different operating systems.
> Add macOS workflow

- tests/automated_fortran_tests/Makefile
The pFUnit submodule was out-dated and not compatible with python 3.12. The submodule has been updated.
> The pFUnit submodule has been updated to be compatible with python 3.12

- .github/workflows/check_stella.yml
- COMPILATION/CMakeLists.txt
Since January 2025 the MacOs system on GitHub can not find the hdf5 libraries anymore during the compilation of stella.
> Since january 2025 the macos system on GitHub can not find the hdf5 libraries anymore during the compilation of stella.

- .github/workflows/check_pyrokinetics.yml
- .gitmodules
- AUTOMATIC_TESTS/Makefile
- AUTOMATIC_TESTS/check_automated_stella_tests_requirements.py
- AUTOMATIC_TESTS/pyrokinetics_tests/test_1_whether_pyrokinetics_loads/empty.in
- AUTOMATIC_TESTS/pyrokinetics_tests/test_1_whether_pyrokinetics_loads/miller_linear_CBC.in
- AUTOMATIC_TESTS/pyrokinetics_tests/test_1_whether_pyrokinetics_loads/miller_linear_CBC_old.in
- AUTOMATIC_TESTS/pyrokinetics_tests/test_1_whether_pyrokinetics_loads/miller_linear_CBC_quick.in
- AUTOMATIC_TESTS/pyrokinetics_tests/test_1_whether_pyrokinetics_loads/test_1a_whether_stella_runs.py
- AUTOMATIC_TESTS/pyrokinetics_tests/test_1_whether_pyrokinetics_loads/test_1b_whether_pyrokinetics_loads.py
- AUTOMATIC_TESTS/pyrokinetics_tests/test_1_whether_pyrokinetics_loads/test_1c_whether_pyrokinetics_loads_for_empty_input.py
- AUTOMATIC_TESTS/requirements.txt
Only the start of these automatic tests have been implemented. To continue it would be useful if stella printed the default variables, since pyrokinetics requires the following namelists to be present:
"parameters_numerical"
"zgrid_parameters"
"geo_knobs"
"millergeo_parameters"
"parameters_physics"
"species_knobs"
"kt_grids_knobs"
> Auto-check whether pyrokinetics can load a stella output.

- COMPILATION/Makefiles/Makefile.dirac
Update CSD3 makefiles for latest version of STELLA. 
Note this works with `make` not `CMake`, see #179
> Update dirac (CSD3) makefile

- STELLA_CODE/geometry/geometry_miller.f90
An empty input file would not run on stella since "kappa=0" by default. I've updated the default Miller parameters to correspond to the Cyclone Base Case (CBC). This way, if someone does not specify a Miller input, a reasonable geometry is created.
> Update default Miller parameters to those of the Cyclone Base Case (CBC)
